spring:
  application:
    name: CoHab
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cohab
    username: magofrays
    password: labubu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: debug
    org.springframework.validation: DEBUG
    by.magofrays: debug
server:
  port: 8080
  address: 0.0.0.0
security:
  jwt:
    secret-key: iluvnastu
    expires-at: 86400
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://cohab-front:8081"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600