spring:
  application:
    name: CoHab
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cohab-db:5432/cohab
    username: magofrays
    password: labubu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    root: INFO
server:
  port: 8080
  address: 0.0.0.0

user:
  max-families: 5

family:
  admin-role-name: ADMIN
  admin-role-value: 100
  user-role-name: MEMBER
  user-role-value: 10
security:
  jwt:
    secret-key: iluvnastu
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://cohab-front:8081"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600